### PR TITLE
Fix color picker bug

### LINKED ISSUE #1464: Color Picker Input filed doesn't works correctly
### Please describe the problem (or idea)
After selecting color picker input the focus freezes on it and other inputs can't be selected

color

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?
rishabhshukla1999

### PR DESCRIPTION
**Pull request by blurry-x-face**
Fixes #1464  

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below
* [x] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

### CODE REVIEW

**Comment by blurry-x-face** [comment]
@publiclab/is-reviewers please review this.

File: examples/lib/defaultHtmlStepUi.js [hunk 1]
```diff
@@ -276,6 +276,21 @@ function DefaultHtmlStepUi(_sequencer, options) {
         });
     });
 
+    $stepAll('.color-picker-target').each(function(i, input) {
```
Comment (HarshKhandeparkar) [inline examples/lib/defaultHtmlStepUi.js]: I think you should use `$step` not `$stepAll`

File: examples/lib/defaultHtmlStepUi.js [hunk 2]
```diff
@@ -276,6 +276,21 @@ function DefaultHtmlStepUi(_sequencer, options) {
...
+      $(input)
+        .data('initValue', $(input).val())
```
Comment (HarshKhandeparkar) [inline examples/lib/defaultHtmlStepUi.js]: Isn't this the same code that is used for every input? If yes, you could just extend the old code, just add another selector string.
`$stepAll('{oldSelector} .color-picker-target')`

Comment (blurry-x-face) [reply examples/lib/defaultHtmlStepUi.js]: No, this isn't the exact same code, this doesn't use focus() method which was causing this bug

Comment (HarshKhandeparkar) [reply examples/lib/defaultHtmlStepUi.js]: Oh.

File: examples/lib/defaultHtmlStepUi.js (hunk 1 above)
Comment (blurry-x-face) [reply examples/lib/defaultHtmlStepUi.js]: Done!

File: examples/lib/defaultHtmlStepUi.js [hunk 3]
```diff
@@ -276,6 +276,21 @@ function DefaultHtmlStepUi(_sequencer, options) {
         });
     });
 
+    $step('.color-picker-target').each(function(i, input) {
```
Comment (HarshKhandeparkar) [inline examples/lib/defaultHtmlStepUi.js]: I am extremely sorry for asking you to change this to `$step`. It is supposed to be `$stepAll` otherwise, it won't work for multiple pickers.
Please change it again.
I am extremely sorry. I forgot what `$stepAll` does, for a moment.

Comment (blurry-x-face) [reply examples/lib/defaultHtmlStepUi.js]: I thought so too that's why I used stepAll but when I changed it to step still it was working fine that's why I pushed commit.

Screenshot from 2020-01-13 00-16-55

Comment (HarshKhandeparkar) [reply examples/lib/defaultHtmlStepUi.js]: Sorry. Please revert it though.

Comment (blurry-x-face) [reply examples/lib/defaultHtmlStepUi.js]: Ok.

**Comment by blurry-x-face** [comment]
@HarshKhandeparkar Done.

**Comment by jywarren** [comment]
Same! Looks great! This could also use a UI test perhaps to protect it in the future! Thank you!!!

**Comment by blurry-x-face** [comment]
@jywarren I've added the test for this!

**Comment by blurry-x-face** [comment]
@HarshKhandeparkar I've made the requested changes, Is this alright?

File: test/ui-2/test/ColorPicker.test.js [hunk 4]
```diff
@@ -7,19 +7,29 @@ beforeAll(async () => {
 
 describe('Color Picker', () => {
   test('Color Picker is not breaking other input fields', async () => {
+    // Wait for .step to load
     await page.waitForSelector('.step');
+    // Click and select crop step
     await page.click('[data-value=\'crop\']');
+    //Check to see of color picker input is present
```
Comment (HarshKhandeparkar) [inline test/ui-2/test/ColorPicker.test.js]: Please add a space at the start of the comment. (to make all the comments look good and readable)

Comment (blurry-x-face) [reply test/ui-2/test/ColorPicker.test.js]: Done!!

**Comment by jywarren** [comment]
Great work!! Thanks!!
