### PR TITLE
Image Sharpening Module added

### LINKED ISSUE #1848: Adding an image sharpening module
Currently in the image sequencer, it seems there is no image sharpening module which can sharpen the image based on the intensity. This might be very useful for use cases where the image is a bit blurred and needs some sharpening. 

_The proposed idea for the module, I believe dates back to issue #1612_ 

So, I managed to implement the functionality by applying a 3x3 convolution filter on a given image and transforming it according to [this resource](https://en.wikipedia.org/wiki/Kernel_(image_processing)#Details:~:text=Depending%20on%20the%20element%20values%2C%20a%20kernel%20can%20cause%20a%20wide%20range%20of%20effects.) 

_The image does get sharpened but as the intensity is increased, the image gets overexposed._ 
Screenshot 2021-03-14 at 6 59 36 PM

Here are the relevant sources that confirm the same. 

https://user-images.githubusercontent.com/58583793/111071402-0676b500-84fc-11eb-9568-2c51461f1df0.mp4

@jywarren and @HarshKhandeparkar, I would like to know if this is the expected behaviour of the algorithm or there is something wrong with my approach so that we can improve upon and add this functionality soon or is there a requirement for such module at all in the first place.

Thanks :)

### PR DESCRIPTION
**Pull request by waridrox**
Closes #1848

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm run test-all`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below
* [ ] Insert-step functionality is working correct as expected.

@jywarren and @HarshKhandeparkar, please tell me where I might have gone wrong which is causing the overexposure of the source image and voice your opinions on the same so that we can work this out together...

Thanks!

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
Can you please explain or send a link explaining how this works?

Thanks.

**Comment by waridrox** [comment]
> Can you please explain or send a link explaining how this works?

Sure, I already mentioned the resource for the implementation in the issue, but here's [another one](https://setosa.io/ev/image-kernels/#twitter-widget-0:~:text=Let's%20walk%20through%20applying%20the%20following%203x3%20sharpen%20kernel%20to%20the%20image%20of%20a%20face%20from%20above.).

- So what we are basically doing is first dividing our image into pixels and then for each 3x3 block of the pixels, we multiply it by the corresponding kernel value and take the sum. 
- The 3x3 matrix approach focuses the weight on the center pixel as the sharpening leads to more vividness in the image governed by [this algorithm ](https://en.wikipedia.org/wiki/Unsharp_masking#Implementation:~:text=In%20the%20example%20below%2C%20the%20image%20is%20convolved%20with%20the%20following%20sharpening%20filter%3A). 
- And to maintain the brightness of the image, the sum of the matrix values should add to one so that the resulting image at least has the same brightness level as the initial image. 

I looked at the implementation of different module filters and saw the implementation of convolution filter that was applied in various places.
Then I took the sharpening array matrix and ran the convolution filter on that taking the input image to achieve the desired result.

File: src/modules/Sharpen/Sharpen.js [hunk 1]
```diff
@@ -0,0 +1,44 @@
+// Generates a 3x3 convolution sharpening kernel
+function kernelGenerator(strength = 1) { //default value of strength set to 1
+
+  let kernel = [[0, -1 * strength, 0], [-1 * strength, 5 * strength, -1 * strength], [0, -1 * strength, 0]];
```
Comment (HarshKhandeparkar) [inline src/modules/Sharpen/Sharpen.js:4]:
```suggestion
  let kernel = [
    [0, -1 * strength, 0],
    [-1 * strength, 5 * strength, -1 * strength],
    [0, -1 * strength, 0]
  ]
```

Just so that it is more readable :)

File: src/modules/Sharpen/Module.js [hunk 2]
```diff
@@ -0,0 +1,46 @@
+/*
+  Sharpen an image
+*/
+module.exports = function Sharpen(options, UI) {
+
+  var defaults = require('./../../util/getDefaults.js')(require('./info.json'));
+  options.sharpen = options.sharpen || defaults.sharpen;
```
Comment (HarshKhandeparkar) [inline src/modules/Sharpen/Module.js:7]: can this option be named something more descriptive like `sharpenStrength`?

File: src/modules/Sharpen/Module.js [hunk 3]
```diff
@@ -0,0 +1,46 @@
+/*
+  Sharpen an image
+*/
+module.exports = function Sharpen(options, UI) {
+
+  var defaults = require('./../../util/getDefaults.js')(require('./info.json'));
```
Comment (HarshKhandeparkar) [inline src/modules/Sharpen/Module.js:6]: Please use `let` instead of `var` wherever possible :)

File: src/modules/Sharpen/info.json [hunk 4]
```diff
@@ -0,0 +1,15 @@
...
+        "sharpen": {
+            "type": "float",
+            "desc": "Amount of sharpening (More sharpening gives more detail, but may lead to overexposure)",
+            "default": 1,
+            "min": 1,
+            "max": 1.5,
+            "step": 0.05
+        }
+    },
+    "docs-link":"#"
```
Comment (HarshKhandeparkar) [inline src/modules/Sharpen/info.json:14]: Is it possible to add docs now?

**Review by HarshKhandeparkar — CHANGES_REQUESTED** [review]
Just a few suggestions :)

Also, can you add a test for this module too?
Thanks!

**Comment by HarshKhandeparkar** [comment]
> Sure, I already mentioned the resource for the implementation in the issue,

Oh, sorry.

> So what we are basically doing is first dividing our image into pixels and then for each 3x3 block of the pixels, we multiply it by the corresponding kernel value and take the sum.
The 3x3 matrix approach focuses the weight on the center pixel as the sharpening leads to more vividness in the image governed by this algorithm .
And to maintain the brightness of the image, the sum of the matrix values should add to one so that the resulting image at least has the same brightness level as the initial image.
I looked at the implementation of different module filters and saw the implementation of convolution filter that was applied in various places.
Then I took the sharpening array matrix and ran the convolution filter on that taking the input image to achieve the desired result.

Noice

File: src/modules/Sharpen/Module.js (hunk 2 above)
Comment (waridrox) [reply src/modules/Sharpen/Module.js]: Sure thing!

File: src/modules/Sharpen/Module.js (hunk 3 above)
Comment (waridrox) [reply src/modules/Sharpen/Module.js]: > Also, can you add a test for this module too?

Actually, I am very new to testing but would love to give it a shot if you can guide me how this data file for example got generated. And is there a way to run individual test file.
Every time I try to run a test on a single file using the command `npm test -- SomeTestFileToRun`, all the tests get executed 😅 instead...

Screenshot 2021-03-17 at 2 13 52 PM

https://github.com/publiclab/image-sequencer/blob/417c1b18261a87acb93ff0d455687e846947add0/test/core/modules/colormap.js#L2-L3

Thanks :)

**Comment by waridrox** [comment]
> Also, can you add a test for this module too?

Actually, I am very new to testing but would love to give it a shot if you can guide me how this data file for example got generated. 
https://github.com/publiclab/image-sequencer/blob/417c1b18261a87acb93ff0d455687e846947add0/test/core/modules/colormap.js#L2-L3
And is there a way to run individual test file.
Every time I try to run a test on a single file using the command `npm test -- test/core/modules/colormap.js`, all the tests get executed 😅 instead...

Screenshot 2021-03-17 at 2 13 52 PM



Thanks :)

**Comment by daemon1024** [comment]
> And is there a way to run individual test file.
> Every time I try to run a test on a single file using the command `npm test -- test/core/modules/colormap.js`, all the tests get executed 😅 instead...

Try `node test/core/modules/colormap.js` instead

**Comment by daemon1024** [comment]
> Actually, I am very new to testing but would love to give it a shot if you can guide me how this data file for example got generated.
> https://github.com/publiclab/image-sequencer/blob/417c1b18261a87acb93ff0d455687e846947add0/test/core/modules/colormap.js#L2-L3
> 

These are standard PNG files converted to base64 encoding, You can use the same image here too but I am not sure how you could generate the benchmark data which should be the sharpened image for the given data.

**Comment by HarshKhandeparkar** [comment]
> I am not sure how you could generate the benchmark data which should be the sharpened image for the given data.

Run the module in the browser, download the PNG and convert it to data URI using an online converter :)

**Comment by waridrox** [comment]
sharpen.js
```javascript
const testModule = require('../templates/module-test'),
//benchmark has the base64 image with sharpening = 1
    benchmark = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAklEQVR4AewaftIAAAGkSURBVKXBMUozYRCA4Xc+ZzYJpBc8h+QAFpaizZZi7wUs7KwsbG3FwsLK2hsIewQPIFiLMTtfdv4MJCBBbf7nkVhhrdaKqvKXiMDdMTNEBGXN3TEz0u7uLu/v72yLCESEpmmotaKqKCvujpnx9vbG3t4e6ebmhpOTE1SVl5cX2rZFRDg8POT5+RlVpdaKuHuoKl3XMZvNeHx8pG1bfiMipIggFVUlzWYzrq6uaNuWtFgscHf6vqfve2qtpIjgu8KKiJAuLy9J8/mc0WiEmdE0DU3TsLOzw2KxIO3v7yMipMLaw8MD6evri8lkwjYRYaPrOjYKa0dHR6RSCr8xM7YV/lNhres60jAM/Mbd2VZYOzg4II3HY4Zh4CcRQbq4uGCjsBIRfPf5+Umtlb7vcXfm8zkfHx+Mx2PS9fU19/f3pDIMA+ns7AwRIU2nU1SVpmkwMyaTCdPplCQipNPTU5K6O6PRiLu7O15fXxERVBV357vz83Nub29JEUGqtSKx4u6YGRsiwk+enp44Pj4muTtmhrJiZiyXS0SEUgoRwV+WyyVmRvoHouS1dlh/5NQAAAAASUVORK5CYII=',
//benchmark1 has base64 image with sharpening = 1.3
    benchmark1 = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAklEQVR4AewaftIAAADsSURBVKXBsa2CUBiG4fc7wYIdtILGhiVsXMCK3hVo6OhcwdbKBWwcQhsbExsYgtD8cpJDYoj3Xq4+j6zHFyLeWCwWNE3DmJkxFjEiCe90OrFer/EejwdJkiCJPM85HA4MZD0CSdzvd9I05SeS8MwMzxFI4ng8kqYpvzEzXjl6kvA2mw1TrFYrJOE5gtvtxlTn85mBI1gul3zC8SVH0LYtn3AEcRwz1X6/Z+DomRn/sd1uuV6veI6gLEsk8RdJeFmW4UUEVVVxuVyQxGw2o+s6Xu12O4qiwDMzBrIeI5J4p65r5vM5ryLeMDOmegL2QE324dz79wAAAABJRU5ErkJggg==',
  optionsTest = require('../templates/options-test');

testModule('sharpen', {sharpenStrength: 1}, benchmark);

optionsTest('sharpen', [{sharpenStrength: 1.3}, {sharpenStrength: 1}], [benchmark1, benchmark]);

```

@HarshKhandeparkar @daemon1024 Any thoughts where I might have gone wrong 😕...Thanks!

Input source image is original 

for intensity = 1 (default sharpening value) the image becomes output

And the status for tests is still not passed:
Screenshot 2021-03-18 at 10 07 08 PM


Apart from this 2 new image files are created for the tests - 
I can't figure out why is the `sharpen-result.png` another image instead of the image on the right. They should both match I think...

Screenshot 2021-03-18 at 10 21 48 PM

**Comment by HarshKhandeparkar** [comment]
You need to specify the input in `testModule` otherwise it used a red square by default.

**Comment by waridrox** [comment]
> You need to specify the input in `testModule` otherwise it used a red square by default.

Thanks, I've added the tests and they pass now finally :)

Screenshot 2021-03-19 at 3 41 59 PM

**Review by daemon1024 — APPROVED** [review]

**Comment by daemon1024** [comment]
Can you rename the PR, I believe it’s not WIP any more.

Also instead of using ‘Addressing’ can you use one of the keywords that GitHub recognises instead. Ref https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by waridrox** [comment]
> Is there still an overexposure issue?

It's just the way the algorithm works, can't do anything about it 😅. To tackle this, I've kept the sharpening intensity such that the image can't get too overexposed to begin with.

**Comment by jywarren** [comment]
This is looking excellent, thanks especially for the test. I'm dismissing the remaining CodeClimate issues. Would love to hear from @HarshKhandeparkar but if @daemon1024 feels confident about this, we can merge!

**Review by jywarren — APPROVED** [review]

**Review by daemon1024 — APPROVED** [review]
Sure! LGTM 😄

**Comment by jywarren** [comment]
Woohoo!!! ✨✨✨✨

**Comment by jywarren** [comment]
This should be a minor release bump of +0.1.0, if anyone wants to adjust the package.json file! 

I'm interested in whether a similar technique could be used to /assess/ sharpness and do focus stacking of an image series... 

https://en.wikipedia.org/wiki/Focus_stacking

**Comment by waridrox** [comment]
> I'm interested in whether a similar technique could be used to /assess/ sharpness and do focus stacking of an image series...

The idea seems so cool! 😄

**Comment by waridrox** [comment]
> This should be a minor release bump of +0.1.0, if anyone wants to adjust the package.json file!

Do we need to change the version in `package-lock.json` as well ? I can create a `fto` out of this if that sounds reasonable :)

**Comment by jywarren** [comment]
I added this update to https://github.com/publiclab/image-sequencer/issues/1751 - and we should go through the release process over there! Thanks!

**Comment by jywarren** [comment]
> > I'm interested in whether a similar technique could be used to /assess/ sharpness and do focus stacking of an image series...
> 
> The idea seems so cool! 😄

Feel free to open a new issue with these notes and CC me!

**Comment by jywarren** [comment]
I guess, one way to think about is:

> a module which analyzes the sharpness of each pixel and replaces any
"blurry" pixel with an alpha transparent pixel.

> we could then repeatedly import images (i.e. import-image module followed
by "overlay-sharpest" module, or something like that) and they'd "knock
out" blurry areas with higher contrast or higher sharpness data. The order
of operations might need tweaking.

I could imagine other ways to do this too, but that seems like a relatively
simple one.

Another idea would be a module which imports a video clip and makes each
frame available to requests from later modules. That would be a little wild
as a module, and maybe would be a separate project.

**Comment by HarshKhandeparkar** [comment]
> Would love to hear from @HarshKhandeparkar

Perfecto
