### PR TITLE
Fix minify Module

### LINKED ISSUE #1420: Minify-Image module not working
### Please describe the problem (or idea)
Minify Image module is not showing the output image.
> What happened just before the problem occurred? Or what problem could this idea solve?
bug

> What did you expect to see that you didn't?
I didnt saw any output image.

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by blurry-x-face**
Fixes #1420 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below
* [x] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

### CODE REVIEW

**Comment by blurry-x-face** [comment]
@publiclab/is-reviewers please review this.
Error was because of this
https://github.com/publiclab/image-sequencer/blob/cded94509b2f76405af80532738600d9d3b7da51/src/modules/MinifyImage/Module.js#L52
https://github.com/publiclab/image-sequencer/blob/cded94509b2f76405af80532738600d9d3b7da51/src/modules/MinifyImage/Module.js#L85

**Comment by root00198** [comment]
The thing was that, this module is not minifying the image... If you compare input image and output image, they both are same.

**Comment by blurry-x-face** [comment]
That's what this PR fixes.
The problem was caused by, I'm assuming #1365

**Comment by root00198** [comment]
https://github.com/publiclab/image-sequencer/pull/1422

Check this PR

**Comment by HarshKhandeparkar** [comment]
Why doesn't this module use pixel manipulation?

**Comment by blurry-x-face** [comment]
This uses compressorjs in browser environment for minifying image so we don't need to use pixel manipulation.

**Comment by HarshKhandeparkar** [comment]
Can it minify GIFs?

**Comment by blurry-x-face** [comment]
It doesnt use compressorjs in node env because our current code uses DOM elements like Blob, atob and even if we import them from `jsom` the compressorjs uses Image() so it is throwing error in node that's why it is not using copressorjs in node but is using `imagemin` but I am getting this error, do you know anything about it @HarshKhandeparkar 
```npm
(node:26177) UnhandledPromiseRejectionWarning: Error: spawn /home/rs007/nodeJs/image-sequencer/node_modules/jpegtran-bin/vendor/jpegtran ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:26177) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by HarshKhandeparkar** [comment]
No, I have no idea about what that error means.

**Comment by blurry-x-face** [comment]
> Can it minify GIFs?

No, It just gives first frame as output image, i'm searching for an alternative
Do you have any idea?

**Comment by blurry-x-face** [comment]
As of now it can just minimize `jpg/jpeg/webp` in browser

**Comment by HarshKhandeparkar** [comment]
> Do you have any idea?

Nope.

File: src/modules/MinifyImage/Module.js [hunk 1]
```diff
@@ -82,8 +82,8 @@ module.exports = function MinifyImage(options, UI) {
     }
 
 
-    function output(image, datauri, mimetype, wasmSuccess) {
-      step.output = { src: datauri, format: mimetype, wasmSuccess, useWasm: options.useWasm };
+    function output(datauri, mimetype) {
```
Comment (jywarren) [inline src/modules/MinifyImage/Module.js]: Hmm, removing wasmSuccess -- can we get a review from @Divy123 ? Thank you!

Comment (HarshKhandeparkar) [reply src/modules/MinifyImage/Module.js]: `wasmSuccess` was from my PR. Why was it removed? Does it not use PixelManipulation? Can you just pass `false` instead of passing nothing?

Comment (blurry-x-face) [reply src/modules/MinifyImage/Module.js]: No, it doesnt use pixel manipulation

Comment (HarshKhandeparkar) [reply src/modules/MinifyImage/Module.js]: Okay. Could you pass `false` instead of nothing?

Comment (blurry-x-face) [reply src/modules/MinifyImage/Module.js]: @HarshKhandeparkar  Done!

**Comment by blurry-x-face** [comment]
Now this works in NodeJs too!

**Comment by jywarren** [comment]
Thank you! This is great!!!
