### PR TITLE
stopped redundant processing and fixed close button.

### LINKED ISSUE #1411: Processing continues even after no video feed
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
ezgif com-video-to-gif (1)

Clicking the take photo button even if camera is disabled continues to do processing on a white canvas.

> What did you expect to see that you didn't?

Expected the process to end because of no video stream

### PR DESCRIPTION
**Pull request by vivek-30**
Fixes #1411.
after this fix the close button works fine , and also when camera access is not provided no redundant processing is there
which solved both the mentioned problem.

### CODE REVIEW

**Comment by vivek-30** [comment]
@HarshKhandeparkar and @jywarren could you please review it.

**Comment by jywarren** [comment]
This looks really nice, thank you! Would you be able to add a GIF of this working and to refine the PR title a little so it's completely clear what the PR is for (as it shows up in our search results for clarity)? 

Thank you!!!

File: src/ui/SetInputStep.js [hunk 1]
```diff
@@ -51,21 +51,31 @@ function setInputStepInit() {
...
+          options.onTakePhoto(canvas.toDataURL());
+        });
+
         document.getElementById('close').addEventListener('click', function () {
           stopStream(stream);
         });
       }
       function handleError(error) {
         console.log('navigator.getUserMedia error: ', error);
+        if(error.message == 'Permission denied' || error.message == 'NotAllowedError' || error.message == 'PermissionDismissedError'){
```
Comment (HarshKhandeparkar) [inline src/ui/SetInputStep.js:66]: Are there any other possible errors?

Comment (vivek-30) [reply src/ui/SetInputStep.js:66]: possibly there may be more , but these are the ones which encounter after camera access denial

Comment (HarshKhandeparkar) [reply src/ui/SetInputStep.js:66]: Shouldn't we show the alert in case of all errors?

**Comment by vivek-30** [comment]
This is the working Gif -

Stop_Processing

Is it ok now ☺️

File: src/ui/SetInputStep.js (hunk 1 above)
Comment (vivek-30) [reply src/ui/SetInputStep.js:66]: Then which kind of error should we have to handle ,any suggestions?

Comment (vivek-30) [reply src/ui/SetInputStep.js:66]: ok, i will add some more checks :)

Comment (HarshKhandeparkar) [reply src/ui/SetInputStep.js:66]: We need not handle any specific error, let us show the alert for every error.

Comment (jywarren) [reply src/ui/SetInputStep.js:68]: OK! Should we go ahead and merge this and do a follow-up, or do you want to add here? Thank you!!!

Comment (vivek-30) [reply src/ui/SetInputStep.js:68]: @HarshKhandeparkar can you look at these new changes.

Comment (vivek-30) [reply src/ui/SetInputStep.js:68]: Please!!

File: src/ui/SetInputStep.js [hunk 2]
```diff
@@ -51,21 +51,48 @@ function setInputStepInit() {
...
+        }
+
+        // when webcam is already used by some other application
+        if(error.message == 'NotReadableError' || error.message == 'TrackStartError' || error.message == 'Concurrent mic process limit'){
+          alert('Your webcam is already in use by some other application');
+        }
+
+        // when some of the requested constraints can't be satisfied like high frame rate or high resolution
+        if(error.message == 'OverconstrainedError' || error.message == 'ConstraintNotSatisfiedError'){
+          console.log('Requested Constraints can not be satisfied ', error);
```
Comment (HarshKhandeparkar) [inline src/ui/SetInputStep.js:86]: Shouldn't there be an alert here too?

Comment (vivek-30) [reply src/ui/SetInputStep.js:86]: But it's not related to browser side and also constrained is passed from the backend so it should be in console i guess. what's your call

Comment (vivek-30) [reply src/ui/SetInputStep.js:86]: if you still want i will change it to `alert`

Comment (HarshKhandeparkar) [reply src/ui/SetInputStep.js:86]: If the user will not be able to see the image, shouldn't the user be notified? Or will the user be able to see the image still?

Comment (vivek-30) [reply src/ui/SetInputStep.js:86]: 1. Error related to the constraints will not affect the image untill we change them in backend, currently there are only 2 constraints -
```js
 {
   video:true
   audio:false,
 }
```
So this is not related to image anyway.

2. Yes user will still see the image

Comment (vivek-30) [reply src/ui/SetInputStep.js:86]: The main cause of the extra processing is due to 📷 access denial and not bcos of some constraints so user should not be alerted for that.

Please correct me if i am wrong 😊

Comment (vivek-30) [reply src/ui/SetInputStep.js:86]: @HarshKhandeparkar when i was adding this check i thought this will help in debbuging ( if the `promise` is rejected ).

User can still use their webcam to capture a image or get a alert for anything else.

Comment (HarshKhandeparkar) [reply src/ui/SetInputStep.js:86]: Ok, thank you!

**Review by jywarren — APPROVED** [review]
Looks great!! Thank you!!!

**Comment by jywarren** [comment]
Nice work!!!!!

**Comment by vivek-30** [comment]
Thank u sir ☺️
