### PR TITLE
Fix Average module editing the UI from the source

### LINKED ISSUE #1467: Average Module Directly changes the UI
# Please describe the problem (or idea)
Currently the average module outputs the average value, directly by changing the UI from the source.

` if (options.step.inBrowser && options.step.ui) $(options.step.ui).find('.details').append('<p><b>Averages</b> (r, g, b, a): ' + sum.join(', ') + '</p>');`

> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by root00198**
Fixes #1467   (<=== Replace `0000` with the Issue Number)

output

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/is-reviewers` for help, in a comment below
* [ ] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

### CODE REVIEW

File: src/modules/Average/Module.js [hunk 1]
```diff
@@ -42,8 +42,8 @@ module.exports = function Average(options, UI) {
       // report back and store average in metadata:
       options.step.metadata.averages = sum;
 
-      // TODO: refactor into a new "display()" method as per https://github.com/publiclab/image-sequencer/issues/242
-      if (options.step.inBrowser && options.step.ui) $(options.step.ui).find('.details').append('<p><b>Averages</b> (r, g, b, a): ' + sum.join(', ') + '</p>');
+      if(options.step.average === undefined) options.step.average = '';
```
Comment (jywarren) [inline src/modules/Average/Module.js]: Can you add a space after the `if` here? Not a big deal but helps us keep code tidy over the long term! Thanks!

File: src/modules/Average/Module.js [hunk 2]
```diff
@@ -42,8 +42,8 @@ module.exports = function Average(options, UI) {
       // report back and store average in metadata:
       options.step.metadata.averages = sum;
 
-      // TODO: refactor into a new "display()" method as per https://github.com/publiclab/image-sequencer/issues/242
-      if (options.step.inBrowser && options.step.ui) $(options.step.ui).find('.details').append('<p><b>Averages</b> (r, g, b, a): ' + sum.join(', ') + '</p>');
```
Comment (jywarren) [inline src/modules/Average/Module.js]: Should we put this ordering help text in the description so people know the channel order? Thanks!

**Comment by jywarren** [comment]
Nice work, thank you!!!
