### PR TITLE
Convert url to blob for large file size download

### LINKED ISSUE #1429: Can't Download Images with higher dimensions
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

We are not able to download images which have high dimension. It gives failed network error.

ezgif com-video-to-gif (1)

> What did you expect to see that you didn't?

Expected to download higher dimension images

### Please show us where to look

https://beta.sequencer.publiclab.org

### PR DESCRIPTION
**Pull request by ataata107**
Fixes #1429   (<=== Replace `0000` with the Issue Number)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [X] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [X] code is in uniquely-named feature branch and has no merge conflicts
* [X] PR is descriptively titled
* [X] ask `@publiclab/is-reviewers` for help, in a comment below
* [X] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

### CODE REVIEW

**Comment by ataata107** [comment]
@publiclab/is-reviewers

**Comment by ataata107** [comment]
Previously files around 1 mb or greater were not possible but this PR makes it possible to download large files

**Comment by LeoDog896** [comment]
Works fine! Since this project is in ES6, why don't you use `let` instead of `var` inside the function scope?

**Comment by ataata107** [comment]
@LeoDog896 Done

**Comment by HarshKhandeparkar** [comment]
This one is outdated. Closing for now, please feel free to rebase and reopen :)

**Comment by jywarren** [comment]
Hi @HarshKhandeparkar i wonder if this would help performance on larger images, and it looks like a relatively complete PR. Should we test it out and consider merging it?

File: examples/lib/defaultHtmlStepUi.js [hunk 1]
```diff
@@ -310,11 +310,23 @@ function DefaultHtmlStepUi(_sequencer, options) {
...
+      }
+      
       var element = document.createElement('a');
-      element.setAttribute('href', step.output);
+      
       element.setAttribute('download', step.name + '.' + fileExtension(step.imgElement.src));
       element.style.display = 'none';
       document.body.appendChild(element);
+      var blob = dataURLtoBlob(step.output);
+      var objurl = URL.createObjectURL(blob);
```
Comment (HarshKhandeparkar) [inline examples/lib/defaultHtmlStepUi.js:328]: What is the difference between this URL and dataURL?

Comment (jywarren) [reply examples/lib/defaultHtmlStepUi.js:328]: I just encountered this in https://github.com/jywarren/bookletize.js and data urls have a length limit in browsers, so they fail on large files, and also blob is more efficient because they don't need to be reencoded. 

I think this is probably worth it!

Comment (HarshKhandeparkar) [reply examples/lib/defaultHtmlStepUi.js:328]: Can we internally use blobs too, then?

Comment (jywarren) [reply examples/lib/defaultHtmlStepUi.js:328]: I think it's possible. We had very very long ago considered different formats for between-module data handoff, including possibly buffers...? i forget, but it was in our very first issue: https://github.com/publiclab/image-sequencer/pull/1#issuecomment-288275324

We could open a new issue with this idea -- basically that default is data-urls, because strings are completely compatible, but if two modules can negotiate that both are compatible with blobs, that's OK too. I think the data-urls worked especially well because they had to be displayed anyways. But now that I think of it I think it's possible to display a blob as well in the browser. Please feel free to open an issue to discuss this!

**Comment by jywarren** [comment]
Merging this! 🎉 at last, thank youuuuuuu!!!

File: examples/lib/defaultHtmlStepUi.js (hunk 1 above)
Comment (jywarren) [reply examples/lib/defaultHtmlStepUi.js:357]: Also note https://stackoverflow.com/questions/7650587/using-javascript-to-display-a-blob

Comment (jywarren) [reply examples/lib/defaultHtmlStepUi.js:357]: I wonder if this would just work, but it depends on the run environment, I imagine:

https://github.com/publiclab/image-sequencer/blob/5298d1e0ecadb83a02111342a72dc3690b27a6ad/src/Run.js#L18-L54

We could add a parameter to drawStep somewhere that evaluates whether the neighboring steps can both handle blobs.

Comment (jywarren) [reply examples/lib/defaultHtmlStepUi.js:357]: I broke this into an issue at https://github.com/publiclab/image-sequencer/issues/1847 !!
