### PR TITLE
Dropdown 'Select a Module' fix

### LINKED ISSUE #1307: Dropdown doesn't close on click
**Please note we are preparing to participate in Google Code-in, and have reserved this issue for GCI participants - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

### Please describe the problem (or idea)

Currently dropdown is not closing when you click on the dropdown icon

### What did you expect to see that you didn't?
 The dropdown should close when dropdown icon is clicked

### Please show us where to look

https://beta.sequencer.publiclab.org

Untitled_ Nov 26, 2019 7_30 PM

### PR DESCRIPTION
**Pull request by tsparksh**
Fixes #1307

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below
* [x] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

dropdownfix

### CODE REVIEW

**Comment by tsparksh** [comment]
@publiclab/reviewers, please check

File: examples/demo.js [hunk 1]
```diff
@@ -8,7 +8,27 @@ var defaultHtmlSequencerUi = require('./lib/defaultHtmlSequencerUi.js'),
 window.onload = function () {
   sequencer = ImageSequencer();
 
-  function refreshOptions() {
+  options = {
+      sortField: 'text',
+      openOnFocus: false,
+      onInitialize: function () {
+          var that = this;
```
Comment (HarshKhandeparkar) [inline examples/demo.js]: Is there a reason why you created this variable?

File: examples/demo.js [hunk 2]
```diff
@@ -8,7 +8,27 @@ var defaultHtmlSequencerUi = require('./lib/defaultHtmlSequencerUi.js'),
...
+          this.$control.on("click", function () {
+              that.ignoreFocusOpen = true;
+              setTimeout(function () {
```
Comment (HarshKhandeparkar) [inline examples/demo.js]: Why is this delay added? Isn't there a better method of doing this(just asking). What exactly does it do anyway?

File: examples/demo.js (hunk 1 above)
Comment (tsparksh) [reply examples/demo.js]: if you mean options variable - because of codeclimat tests.
It added a default value for it so this code should not break anything

Comment (HarshKhandeparkar) [reply examples/demo.js]: no, the `that` variable? It seems redundant to me.

File: examples/demo.js (hunk 2 above)
Comment (tsparksh) [reply examples/demo.js]: The actual time difference between the click and onFocus is not controlled by the user and is usually about 2-5 milliseconds. Waiting for 50 is more than enough to prevent unexpected behavior.

File: examples/demo.js (hunk 1 above)
Comment (tsparksh) [reply examples/demo.js]: because we cant use the parent’s “this” in
```
this.$control.on("click", function () {
            that.ignoreFocusOpen = true;
            setTimeout(function () {
                that.ignoreFocusOpen = false;
            }, 50);
        });
```

Comment (HarshKhandeparkar) [reply examples/demo.js]: Can you instead use an arrow function? Arrow functions do not have their own scoped `this`.

File: examples/demo.js (hunk 2 above)
Comment (HarshKhandeparkar) [reply examples/demo.js]: So the dropdown opens when `onFocus` is triggered?

Comment (HarshKhandeparkar) [reply examples/demo.js]: Then what happens `onClick`?

File: examples/demo.js (hunk 1 above)
Comment (tsparksh) [reply examples/demo.js]: I’m not sure that old browsers support arrow functions

Comment (HarshKhandeparkar) [reply examples/demo.js]: We already use arrow functions. Don't worry. Old browsers don't support many things. Ultimately, the benefits of ES6 are much more. Just because of browser support, we can't ignore the benefits. Anyway, I don't think anyone will use IS on IE. Similarly, we dropped support for NodeJS 6.0 because it doesn't support GPU acceleration which is crucial. Thanks.

File: examples/demo.js (hunk 2 above)
Comment (tsparksh) [reply examples/demo.js]: When the input is not focused and you click, first fires the onFocus event and then a click event on this.$control
When you click on the input while it is focused and the dropdown is shown, it's the opposite - first fires onBlur, then click and finally onFocus

Comment (HarshKhandeparkar) [reply examples/demo.js]: I was asking what each event does. Not what triggers it.

Comment (HarshKhandeparkar) [reply examples/demo.js]: What happens when an event is triggered? What does it do?

Comment (tsparksh) [reply examples/demo.js]: These events used for correct closing dropdown when we clicking outside the text but still in the box of dropdown. We get the same functionality as with openOnFocus set to true, except we don't get this strange unable-to-close behavior.

>So the dropdown opens when onFocus is triggered?
Yes, but only after 50 miliseconds of clicking on area of dropdown to protect from reopening

File: examples/demo.js (hunk 1 above)
Comment (tsparksh) [reply examples/demo.js]: Like this?
```
this.$control.on("click", (e) => {
    this.ignoreFocusOpen = true;
    setTimeout(function () {
        this.ignoreFocusOpen = false;
    }, 50);
});
```

Comment (HarshKhandeparkar) [reply examples/demo.js]: yes. great.

File: examples/demo.js (hunk 2 above)
Comment (HarshKhandeparkar) [reply examples/demo.js]: Ok great.

File: examples/demo.js (hunk 1 above)
Comment (tsparksh) [reply examples/demo.js]: So can you accept gci task now?

**Comment by HarshKhandeparkar** [comment]
Do you think adding a few comments to the code would help?

**Comment by HarshKhandeparkar** [comment]
I am not a mentor sorry😅. I am just a student and reviewing others' PRs.

**Comment by tsparksh** [comment]
@keshav234156 , can you accept my GCI task?

File: examples/demo.js [hunk 3]
```diff
@@ -8,7 +8,26 @@ var defaultHtmlSequencerUi = require('./lib/defaultHtmlSequencerUi.js'),
...
 
-  function refreshOptions() {
+  options = {
+      sortField: 'text',
+      openOnFocus: false,
+      onInitialize: function () {
+          this.$control.on("click", () => {
+            this.ignoreFocusOpen = true;
+            setTimeout(() => {
+              this.ignoreFocusOpen = false; // trigger onFocus and open dropdown
```
Comment (HarshKhandeparkar) [inline examples/demo.js]: Sorry but I forgot to tell you that comments need to follow certain rules from now on. We want to increase the consistency of docs in the codebase. Please start with a Capital letter and end with a full stop.

Comment (tsparksh) [reply examples/demo.js]: Sure.

Comment (tsparksh) [reply examples/demo.js]: Is it okey now?

Comment (HarshKhandeparkar) [reply examples/demo.js]: Please add full stops. Sorry for delaying this.

Comment (tsparksh) [reply examples/demo.js]: Like this? Sorry I’m not sure that understood word “full stop” correctly

**Comment by jywarren** [comment]
Awesome work! Thank you!
