### PR TITLE
Detect and Parse string separated module names

### LINKED ISSUE #731: Detect and parse any input syntax type (string, obj) in addSteps, replaceImage methods
I noticed that `sequencer.addSteps('invert,ndvi')` doesn't work because it doesn't recognize and parse the string. We should detect commas and pre-filter the input using `sequencer.importString()` so that we can simply pass multiple steps in via `addSteps()`

This shouldn't be too hard, and we can add this as an example to the README too, where actually we don't show the use of string syntax -- we can demonstrate in a new subsection:

```

Use string syntax (see below) to add multiple steps and configurations quickly by passing a string to `sequencer.addStep()`:

...example...

```

This'd be a really nice refinement!

### PR DESCRIPTION
**Pull request by VibhorCodecianGupta**
Fixes #731 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` and `@publiclab/is-reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

Thanks!

### CODE REVIEW

**Comment by VibhorCodecianGupta** [comment]
@publiclab/is-reviewers

**Comment by VibhorCodecianGupta** [comment]
@publiclab/is-reviewers

**Comment by HarshKhandeparkar** [comment]
Can we implement this in a way that absolutely any syntax can be interpreted. Like array of string steps, array of objects containing stepName and options, string of steps.

String of steps can be either comma selarated or space separated

Array/string of string steps can optionally have options like used in urlHash i.e. 

`'stepName{option1=val1,option2=val2}'` 

Array of strings like the above one can be passed or a string containing many such thing syntaxes can be passed.

Also JSON as string can be passed.

This can be converted into a util func. Maybe `parseSyntax`??

Can the function detect the different syntaxes and parse them accordingly? Is this feasible? What are your thoughts about this?

cc @jywarren @publiclab/is-reviewers

**Comment by jywarren** [comment]
I think this would be great and we could start with a test that
demonstrates each type of input! +1000000

File: src/ImageSequencer.js [hunk 1]
```diff
@@ -245,6 +245,32 @@ ImageSequencer = function ImageSequencer(options) {
...
+
+  // Parses input string and returns array of module names
+  function parseSyntax(str) {
+    let stringifiedNames = str.replace(/\s/g, '')
+    let moduleNames = stringifiedNames.split(',')
+    return moduleNames
+  }
+
+  // imports string of comma separated module names to sequencer steps
+  function stringToStep(str) {
```
Comment (jywarren) [inline src/ImageSequencer.js]: Just wondering if this is slightly redundant with `stringToJSON()`?

https://github.com/publiclab/image-sequencer/blob/ac57b32ec636b7b38bae5d9b53a5d0dd6c3feadd/src/ImageSequencer.js#L289-L297

File: README.md [hunk 2]
```diff
@@ -224,6 +224,12 @@ which are to be added, in that particular order.
 optional_otions is just additional parameters, in object form, which you might
 want to provide to the modules. It's an optional parameter.
 
+Use string syntax (see below) to add multiple steps and configurations quickly by passing a string to `sequencer.addStep()`:
+
+```js
+sequencer.addSteps('invert, channel');
```
Comment (jywarren) [inline README.md]: in theory we should not include spaces here, though maybe it's not such a big deal if it can handle it?

File: src/ImageSequencer.js (hunk 1 above)
Comment (VibhorCodecianGupta) [reply src/ImageSequencer.js]: I took the `','` check out of the `stringToJSON()` and generalised it in `detectSyntax` and `parseSyntax` for this reason. I think for expanding this functionality, wherever we need to detect and parse a comma-separated string, we could use the new functions. For example, here `stringToJSON()` checks for comma separated string and then returns a JSON step. The if condition would have to be checked a lot, in say, support for arrays and object-based steps. I'll push more code where I think this will be a modular approach. Incoming!

File: README.md (hunk 2 above)
Comment (VibhorCodecianGupta) [reply README.md]: Yes, `parseSyntax()` already handles spaces :D

**Comment by VibhorCodecianGupta** [comment]
@HarshKhandeparkar the array of steps approach is already handled by IS, there is a test case for that as well. The step name with an object containing parameter values (stringified) would be a nice addition, I'll do that, then. Shall we also handle an array of stringified step names and their objects (containing parameters) ?

cc @jywarren

**Comment by HarshKhandeparkar** [comment]
We can first parse JSON strings into normal js objects. After that, we can do the same that we do to array of steps if it is a JSON array and if it is a JSON object, we can do what we do to objects.

So:
1. See the data type {string(JSON or space separted steps), object, array}.
2. If it is an array, do something.
3. If it is an object, do something.
4. If it is a string, do further categorization.

String:
1. If it is JSON, it can be an array or an object, we know what to do.
2. If it has space separted module named, we know what to do.
3. New idea: sequencer has a `toString()` option which exports module names as well as options. You can see it in the website url exported as a *urlHash Parameter*. Can we parse such a thing.

Another thing:
1. If it is an object, it can contain both steps as well as options, how will that object be formatted. Maybe key name will be module name and it will have a value containing the options.


Some of this may be useless or difficult to implement or already done in the same or a different way.

Cc @VibhorCodecianGupta

**Comment by jywarren** [comment]
Awesome!!!!

**Comment by HarshKhandeparkar** [comment]
Vibhor, what do the checkboxes indicate? What you have already implemented or was already implemented? And do the unchecked boxes mean that you are not going to work on it or something? I didn't quite get what you have done there as you have also checked JSON which is not yet supported.

**Comment by VibhorCodecianGupta** [comment]
@HarshKhandeparkar The checked ones are/will be implemented in this PR itself. The unchecked ones, I'll get them working as follow-ups most likely. Or maybe in this PR too, if feasible

**Comment by HarshKhandeparkar** [comment]
Ok.

**Comment by VibhorCodecianGupta** [comment]
This is the flow I've tried to achieve:

Following inputs are handled here, `invert,channel`, `brightness{brightness:80}` and `crop{x:120|y:90},average{}`

`detectSyntax()` checks for presence of `,` OR `{`. Any one of them indicates one of the above mentioned formats. `parseSyntax()` then splits them from the comma and the resulting array is passed to `stringToJSONstep` which can parse the array elements and separate the options from the module names if present, otherwise just return empty options object. All this happens inside `stringToJSON`, which is then called inside `stringToStep`, responsible for adding the steps in the insert function

I have written tests for the same, and they are all passing. However, Travis is failing for some reason on the old tests inside `image-sequencer` test suite. It looks like the tests for adding steps to an image name reference are failing. Is this expected behaviour? Probably these tests need to be rewritten altogether without the image references ever since the API restructure (#824)?

A suggestions, we can also make the `addSteps` method compatible with, say, a JSON module. If a user creates a JSON file of the steps and configurations and requires it inside addSteps, we should be able to handle that.

@jywarren

**Comment by HarshKhandeparkar** [comment]
Looking into travis...

**Comment by HarshKhandeparkar** [comment]
It is pretty difficult to track. I have a bad inet conn. I will look into it and find out the problem in a few min.
Btw, can you please help me with [this](https://codepen.io/imnotacoder/pen/NmyWmx?editors=0011) codepen? It is not wroking very well. I would like to get your views. Please message me on gitter if you find a bug or want to suggest something. This is for IS. You don’t have to know anything about the lib I have used but I want help with syntax errors. Codepen doesn’t log anything to my console(maybe because I am using safari on ios or maybe because of inet). Thanks.

**Comment by HarshKhandeparkar** [comment]
Oh I found the problem  with your code. I think it is outdated.
If you compare this
https://github.com/publiclab/image-sequencer/blob/6fa8b1b8808d202355f51f9e3471d2f0423d3288/test/core/modules/image-sequencer.js#L84-L104
With the job log
```
 addSteps(["name"]) adds a step
    ✔ Length of steps increased by two
    ✔ Correct Step Added
    ✔ Correct Step Added
  addSteps("name",o) adds a step
    ✔ Length of steps increased
    ✔ Correct Step Added
  addSteps("image","name",o) adds a step
Module t not found.
    TypeError: Cannot read property 'description' of undefined
        at insertStep (http://localhost:37595/bundle.js:71378:49)
        at InsertStep (http://localhost:37595/bundle.js:71416:3)
        at AddStep (http://localhost:37595/bundle.js:70690:33)
        at Object.addSteps (http://localhost:37595/bundle.js:70949:29)
        at Test.<anonymous> (http://localhost:37595/bundle.js:76892:13)
        at Test.bound [as _cb] (http://localhost:37595/bundle.js:68041:32)
        at Test.run (http://localhost:37595/bundle.js:68060:10)
        at Test.bound [as run] (http://localhost:37595/bundle.js:68041:32)
        at next (http://localhost:37595/bundle.js:67835:19)
        at onNextTick (http://localhost:37595/bundle.js:68957:12)
npm ERR! Test failed.  See above for more details.
The command "npm test" exited with 1.
```

The third teet has no “image” in the latest code but has it in the job log.

**Comment by HarshKhandeparkar** [comment]
Try rebasing

**Comment by HarshKhandeparkar** [comment]
Thanks.

**Comment by HarshKhandeparkar** [comment]
How did the codecov decrease?

**Comment by HarshKhandeparkar** [comment]
Also please see this https://github.com/publiclab/image-sequencer/issues/849#issuecomment-483733931 (not related to this issue, sorry). Btw I fixed the pen(kind of). Only one part is not working but I don't think it is a syntax error but rather a library issue. Tell me if you see any obvious errors otherwise just have a look at the pen demo. Thanks.

File: src/ImageSequencer.js [hunk 3]
```diff
@@ -237,6 +237,32 @@ ImageSequencer = function ImageSequencer(options) {
     return `sequencer -i [PATH] -s ${cliStringSteps} -d '${JSON.stringify(cliOptions)}'`
   }
 
+  // Checks if input is a string of comma separated module names
+  function detectSyntax(str) {
+    let result = (str.includes(',') || str.includes('{')) ? true : false
```
Comment (HarshKhandeparkar) [inline src/ImageSequencer.js]: The ternary operator `?` is not required as it just returns true/false

Comment (HarshKhandeparkar) [reply src/ImageSequencer.js]: You can directly return it as well.
```js
return (str.includes(',') || str.includes('{'))
```

File: test/core/modules/image-sequencer.js [hunk 4]
```diff
@@ -103,29 +104,54 @@ test('addSteps("name",o) adds a step', function(t) {
...
+  sequencer.addSteps('channel,invert')
+  t.equal(sequencer.steps.length, 7, 'Length of steps increase')
+  t.equal(sequencer.steps[5].options.name, "channel", "Correct Step Added");
+  t.equal(sequencer.steps[6].options.name, "invert", "Correct Step Added");
+  t.end()
+})
+
+test('addSteps("name{parameter:value},name{parameter:value}") adds two steps', function(t) {
+  sequencer.addSteps('brightness{brightness:80},average{}')
+  t.equal(sequencer.steps.length, 9, 'Length of steps increase')
```
Comment (HarshKhandeparkar) [inline test/core/modules/image-sequencer.js]: Isn't there a better way to keep track of how many steps were added?

File: src/ImageSequencer.js (hunk 3 above)
Comment (VibhorCodecianGupta) [reply src/ImageSequencer.js]: Won't make much of a difference, i guess?

File: test/core/modules/image-sequencer.js (hunk 4 above)
Comment (VibhorCodecianGupta) [reply test/core/modules/image-sequencer.js]: We're brute forcing our tests anyway. We could start removing steps after each test suite, but I think it's fine for now. Maybe a future issue when tests are being overhauled

File: src/ImageSequencer.js (hunk 3 above)
Comment (HarshKhandeparkar) [reply src/ImageSequencer.js]: Yeah. Just makes the code cleaner. If you are going to push more commits, change this as a side effect.

**Comment by HarshKhandeparkar** [comment]
I am looking into jQuery error in travis.

**Comment by HarshKhandeparkar** [comment]
I think the crop module is causing problems.
https://github.com/publiclab/image-sequencer/blob/main/src/modules/Crop/Ui.js

**Comment by jywarren** [comment]
Hmm, no, i'm not sure about `ReferenceError: $ is not defined`... but just chiming in to say i agree coverage decrease is OK -- pretty minimal!

File: README.md [hunk 5]
```diff
@@ -241,7 +241,39 @@ If multiple images are to be added, `modules` is an array, which holds the names
...
+
+```js
+sequencer.addSteps('invert,channel');
+sequencer.addSteps(['invert','channel']);
+```
+
+For passing default configurations:
+
+```js
+sequencer.addSteps('brightness{}');
```
Comment (jywarren) [inline README.md]: Here, we might say `{}` is optional?

File: README.md [hunk 6]
```diff
@@ -241,7 +241,39 @@ If multiple images are to be added, `modules` is an array, which holds the names
 to be added, in that particular order.
 
 optional_otions is just an optional parameter, in object form, which you might
-want to provide to the modules. 
+want to provide to the modules.
+
+A variety of syntaxes are supported by Image Sequencer to add multiple steps and configurations quickly for module chaining. This can be achieved by passing strings to `sequencer.addStep()`:
```
Comment (jywarren) [inline README.md]: We might say the two major ones are "string syntax" and JSON, where string syntax is designed to be as compact and URL-friendly as possible, and JSON is capable of more complex sequences.

File: src/ImageSequencer.js [hunk 7]
```diff
@@ -237,6 +237,32 @@ ImageSequencer = function ImageSequencer(options) {
     return `sequencer -i [PATH] -s ${cliStringSteps} -d '${JSON.stringify(cliOptions)}'`
   }
 
+  // Checks if input is a string of comma separated module names
+  function detectSyntax(str) {
```
Comment (jywarren) [inline src/ImageSequencer.js]: If it returns boolean, should we name this `detectStringSyntax`? Or should we return "json" and "string"?

Comment (jywarren) [reply src/ImageSequencer.js]: Also, does this detect JSON saved as a string, AND native JSON objects in JS? Maybe we should specify! Thanks!

File: src/ImageSequencer.js [hunk 8]
```diff
@@ -237,6 +237,32 @@ ImageSequencer = function ImageSequencer(options) {
...
+    let result = (str.includes(',') || str.includes('{')) ? true : false
+    return result
+  }
+
+  // Parses input string and returns array of module names
+  function parseSyntax(str) {
```
Comment (jywarren) [inline src/ImageSequencer.js]: What about calling this `parseStringSyntax()`?

**Comment by HarshKhandeparkar** [comment]
I don't know much about testing so i was curious to know if this was the expected behaviour. @jywarren please have a look at issue #849. This is important. Sorry for telling here.

File: src/ImageSequencer.js (hunk 1 above)
Comment (jywarren) [reply src/ImageSequencer.js]: OK, shall we just add in the docs the difference between them? Also, should it be `stringToSteps`?

File: src/ImageSequencer.js (hunk 7 above)
Comment (HarshKhandeparkar) [reply src/ImageSequencer.js]: I had the same thoughts

_Sent from my OnePlus3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

Comment (VibhorCodecianGupta) [reply src/ImageSequencer.js]: @jywarren fir now, this and `parseSyntax()` detect and handle normal comma separated strings AND JSON saved as strings. I mentioned above a possible improvement of supporting JSON modules as well:

> A suggestions, we can also make the `addSteps` method compatible with, say, a JSON module. If a user creates a JSON file of the steps and configurations and requires it inside addSteps, we should be able to handle that.

Would be a good addition, perhaps a follow up to this one?

**Comment by VibhorCodecianGupta** [comment]
@jywarren made the requested changes

File: src/ImageSequencer.js (hunk 7 above)
Comment (jywarren) [reply src/ImageSequencer.js]: Yep that'd be great!

**Comment by jywarren** [comment]
This looks good now once it passes tests! Thanks!!!

**Comment by VibhorCodecianGupta** [comment]
@jywarren wondering why the tests are failing. The PR doesn't affect the part of the code that is failing, and I haven't seen this error in any other Travis runs...

**Comment by HarshKhandeparkar** [comment]
Maybe something wasn't working before which your PR fixed by mistake. Coincidentally the thing that wasn't working before had no check for `inBrowser` but used jQuery directly. By `a thing` I mean a piece of code.
This is a big story but it may be true, maybe even partially.

**Comment by VibhorCodecianGupta** [comment]
@HarshKhandeparkar I figured it out this morning. The test I added for the new inputs had the `crop` module code. The `UI.js` in crop module handles some jquery for the `imageselectarea` plugin, which will only run in the browser environment, which caused the reference error of `$` not being defined. Probably we should add an `inBrowser` check for the `$imgEl` part? For fixing tests, I'll simply test it with some other module and push the code 
cc @jywarren

**Comment by HarshKhandeparkar** [comment]
See the Crop.js and Module.js files. They run the Ui.js file only when inBrowser is on. Should it cause probs? All the modules are benchmarked by travis and they aren't broken so why should this happen? I had actually linked to the crop yesterday.
> I think the crop module is causing problems.
https://github.com/publiclab/image-sequencer/blob/main/src/modules/Crop/Ui.js

I had linked to Ui.js but I still don't think it should cause probs. Try commenting the require for ui.js and push. You can also try putting a console.log inside the inBrowser if statement, see if it is logged.

**Comment by HarshKhandeparkar** [comment]
Ah. See this
https://github.com/VibhorCodecianGupta/image-sequencer/blob/a07adde255b8f52dd3e2c4bf6dba8fdfc3606609/test/core/modules/image-sequencer.js#L29

Try setting `inBrowser` to false here. I am not sure if `ui: false` does that(mostly not).

**Comment by HarshKhandeparkar** [comment]
IS tries to set inBrowser itself but maybe it isn't able to.
https://github.com/publiclab/image-sequencer/blob/6fa8b1b8808d202355f51f9e3471d2f0423d3288/src/ImageSequencer.js#L1-L2

And yes, the ui flag doesn't do much.

**Comment by VibhorCodecianGupta** [comment]
@jywarren tests passing. Is this ready to merge? Follow up task: Support for JSON steps.
@HarshKhandeparkar I'll try out some possibilities here and see why this is happening.

**Comment by HarshKhandeparkar** [comment]
What did you do to tix the tests?

**Comment by VibhorCodecianGupta** [comment]
For now, I removed the crop module from my test and used the brightness module instead. That's why I said I'll try tweaking with that module and see why the reference error was there. It shouldn't interfere with this functionality since that error is not innate to parsing functions but the module itself. I'll get back here when I find something.

**Comment by HarshKhandeparkar** [comment]
Oh ok. Btw, you had passed params to it right. Try doing the same in node on the `main` branch of publiclab. Run it with params and see if it gives an error.

**Comment by VibhorCodecianGupta** [comment]
@jywarren fixed conflicts, ready to go!

**Comment by VibhorCodecianGupta** [comment]
@jywarren fixed conflicts, ready to go!

**Comment by jywarren** [comment]
Awesome!!! Thanks! I'll publish a release now!
