### PR TITLE
Fix insert step and allow "closing" it

### LINKED ISSUE #918: Problem with add step button
### Add step button looks like this when we add the new step between the two steps

button

### Please show us where to look

https://beta.sequencer.publiclab.org

### Browser, version, and operating system
 Chrome(latest version) ,Linux 
## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### LINKED ISSUE #919: Selectize isn't working on "insert step"
### When we append new step between the two steps then the selectize step is not working to select the modules.
button

### Please show us where to look

https://beta.sequencer.publiclab.org

### Browser, version, and operating system
Chrome(latest version) and Linux

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by HarshKhandeparkar**
Fixes https://github.com/publiclab/image-sequencer/issues/640
Fixes #918
Fixes #919

Insert step button no longer appends more than once.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

Thanks!

### CODE REVIEW

File: examples/lib/intermediateHtmlStepUi.js [hunk 1]
```diff
@@ -60,11 +60,29 @@ function IntermediateHtmlStepUi(_sequencer, step, options) {
...
     addStepUI = parser.parseFromString(addStepUI, "text/html").querySelector("div")
-    step.ui
+
+    var toggleDiv = () => {
+      $(step.ui.querySelector('.insertDiv')).fadeToggle(200).collapse('toggle')
+      if ($(step.ui.querySelector('.insert-text')).css('display') != "none"){
+        $(step.ui.querySelector('.insert-text')).fadeToggle(200, () => {$(step.ui.querySelector('.no-insert-text')).fadeToggle(200)})
+      }
+      else {
+        $(step.ui.querySelector('.no-insert-text')).fadeToggle(200, () => {$(step.ui.querySelector('.insert-text')).fadeToggle(200)})
```
Comment (Divy123) [inline examples/lib/intermediateHtmlStepUi.js]: I think we should migrate to normal functions here instead of arrow functions as it may not be supported by some browsers.

Comment (HarshKhandeparkar) [reply examples/lib/intermediateHtmlStepUi.js]: I had asked @jywarren about this, he said I can use these if they are supported and they are.

I think all modern (>IE) browsers support arrow functions and template literals. Including EdgeSafari everything.

https://kangax.github.io/compat-table/es6/

**Comment by HarshKhandeparkar** [comment]
@Divy123 arrow functions are supported by all browsers excluding IE

**Comment by Divy123** [comment]
Still I think leaving an exception is not a good practice.

**Comment by HarshKhandeparkar** [comment]
> Still I think leaving an exception is not a good practice.

IE is not used by anybody and even if somebody uses it I don't think ImageSequencer itself will work on it. Also, arrow functions have been used earlier in some PRs and they are in some `module.js` files and also in `defaultHtmlStepUi.js` file too I think. Or maybe in `demo.js`. I have seen them somewhere for sure.

**Comment by Divy123** [comment]
Can you please find out those snippets so that things can be rectified.
Also one of my friends has tested it on IE.

**Comment by Divy123** [comment]
@jywarren I think this idea is quite good. Maybe we can use Babel for this issue?

**Comment by HarshKhandeparkar** [comment]
https://www.w3schools.com/browsers/ refers to Edge and IE as the same entity though they are not. Edge is updated and IE is not. Anyways whoever uses default windows10 browser uses Edge, therefore, it is the third most used. But if we are going to use babel then we don't need to worry. This can be merged and then compiled in a separate PR.

**Comment by Divy123** [comment]
Sure but as of now even I was directed to use normal functions and I don't think it to be a difficult task.

**Comment by HarshKhandeparkar** [comment]
> Sure but as of now even I was directed to use normal functions on one of my PR and I don't think it to be a difficult task.

Ok I'll do that.

**Comment by HarshKhandeparkar** [comment]
@publiclab/is-reviewers please review this.

**Comment by HarshKhandeparkar** [comment]
@Divy123 I have made the changes. Please check them out.

**Comment by HarshKhandeparkar** [comment]
@Divy123 can you open the issue for babel? We can discuss everything there. This might benefit us a lot. Will make the source code a lot cleaner and simpler.

**Comment by HarshKhandeparkar** [comment]
@jywarren please check this out.

**Comment by jywarren** [comment]
This looks great. Are we all good to merge here once it's been rebased? Thank you!!!

**Comment by HarshKhandeparkar** [comment]
My exams are starting. So I will not be available until 30th January. I will fix the conflicts later.

**Comment by HarshKhandeparkar** [comment]
I have merged with main. @publiclab/is-reviewers please review.

**Comment by HarshKhandeparkar** [comment]
@publiclab/is-reviewers @jywarren I have rebased but due to the preview images fix, the console logs are creating a lot of lag. Even when the page is first loaded, the console logs create a lot of lag. On an old PC/browser the browser might even crash. We will either have to add an option for verbose/non-verbose mode or process everything on an alternate thread. Thoughts?

console-lag

**Comment by HarshKhandeparkar** [comment]
@jywarren can you please merge my PRs before the other ones since I will not be able to touch my PC until 16th of april. I don't know if I will get time past that date as well.

**Comment by jywarren** [comment]
Hi! I'm merging this, but I'd like to suggest we put the "close insert step" button in the Insert Step box itself, because where it is now is a bit confusing -- not clear that you're closing the Insert Step box. I think it's OK for now but will open a new issue and hopefully we can get this modified!

Great work @HarshKhandeparkar !!!

...

Hmm, actually now that I am trying to rebase it, I see that some of this was solved in https://github.com/publiclab/image-sequencer/pull/712/, and I am not sure how to proceed here. 

I'm really sorry @HarshKhandeparkar but I think I need to ask you and @Mridul97 to try to figure this out before we can merge here. I can't quite tell what is the "close box" button code and what is the "fixing insert step" part. 🙁  Sorry!!!

**Comment by HarshKhandeparkar** [comment]
Jywarren my PR changes the intermediateHtmlStepUi.js file whereas #712 fixes defaultHtmlStepUi.js where the other file was not required properly.

**Comment by HarshKhandeparkar** [comment]
@jywarren I just merged with main but it is still showing conflicts.

**Comment by HarshKhandeparkar** [comment]
@jywarren I have made some changes but I couldn't check those out. You or someone else will have to check them out locally. Sorry.

**Comment by jywarren** [comment]
@Harshithpabbati are you able to test this out perhaps? Or @Divy123 ? Thank you, much appreciated!

**Comment by Harshithpabbati** [comment]
> @Harshithpabbati are you able to test this out perhaps? Or @Divy123 ? Thank you, much appreciated!

Just a min i will check this. @jywarren

**Comment by Divy123** [comment]
Checking it .

**Comment by Harshithpabbati** [comment]
box
Why are there 3 boxes to close. @HarshKhandeparkar

**Comment by Harshithpabbati** [comment]
Sorry that was by mistake. I closed the pull req

**Comment by Harshithpabbati** [comment]
just a small change everything is good!!.

**Comment by Harshithpabbati** [comment]
But the thing was I can't find that change in pr.

**Comment by Divy123** [comment]
harsh
Two close buttons appearing nearby each other.
The Add steps button is not appearing and  working.
Please look into these two.
Thanks!!

**Comment by Harshithpabbati** [comment]
> harsh
> Two close buttons appearing nearby each other.
> The Add steps button is not appearing and working.
> Please look into these two.
> Thanks!!

Add step button is working @Divy123

**Comment by Harshithpabbati** [comment]
And other one after adding from add step the button is not changing to add button.
see this 
add

**Comment by Harshithpabbati** [comment]
> And other one after adding from add step the button is not changing to add button.
> see this
> add

After adding from the add button then the button shows the vice-versa but functions in the correct way.

File: dist/image-sequencer-ui.js [hunk 2]
```diff
@@ -762,8 +762,9 @@ var urlHash = require('./urlHash.js'),
 
 function IntermediateHtmlStepUi(_sequencer, step, options) {
   function stepUI() {
-    return '<div class="row insertDiv">\
+    return '<div class="row insertDiv collapse">\
         <div class="col-md-6 col-md-offset-2" style="margin-top:5%">\
+	<button class="btn btn-primary close-insert-box"><i class="fa fa-times" aria-hidden="true"> Close</button>\
```
Comment (Harshithpabbati) [inline dist/image-sequencer-ui.js]: Remove this line.

Comment (Harshithpabbati) [reply dist/image-sequencer-ui.js]: There are two close buttons.

**Comment by HarshKhandeparkar** [comment]
Will fix #918 and #919 soon. Almost done with it locally.

**Comment by HarshKhandeparkar** [comment]
@jywarren I am tired rebasing this. Please try to merge it.

fix-insert-step

**Comment by HarshKhandeparkar** [comment]
I have also fixed the dropdown icon.

**Comment by HarshKhandeparkar** [comment]
@jywarren this has been open for 3 months now. I have rebased it several times. Please try to merge it. I have made all the suggested changes like the close button inside the div. Also I have fixed the dropdown icon which wasn't getting rotated.

**Comment by HarshKhandeparkar** [comment]
@publiclab/is-reviewers

**Comment by HarshKhandeparkar** [comment]
The add step buttons are broken everywhere. Even on beta.sequencer.publiclab.org. That can be fixed in a separate pr.

**Comment by Harshithpabbati** [comment]
> The add step buttons are broken everywhere. Even on beta.sequencer.publiclab.org. That can be fixed in a separate pr.

Broken ???. Do you mean it is not visible???

**Comment by HarshKhandeparkar** [comment]
It is not responsive

**Comment by HarshKhandeparkar** [comment]
Only on xs screens

**Comment by HarshKhandeparkar** [comment]
It works well on small screens. Try to open an issue for that.

**Comment by Harshithpabbati** [comment]
ok!! I will check it and if needed I will make it an fto.

**Comment by HarshKhandeparkar** [comment]
Please review this as well :)

**Comment by Harshithpabbati** [comment]
Yeah trying to check it local. :smile:

**Comment by Harshithpabbati** [comment]
@HarshKhandeparkar sorry for this. You need to still make few changes as the quick add isn't working in the insert step.

File: examples/demo.js [hunk 3]
```diff
@@ -197,8 +197,8 @@ window.onload = function() {
         step.options.step.imgElement.src = reader.result;
       else
         step.imgElement.src = reader.result;
-      insertPreview.updatePreviews(reader.result,'addStep');
-      insertPreview.updatePreviews(sequencer.steps[0].imgElement.src,'insertStep');
+      insertPreview.updatePreviews(reader.result,'#addStep');
+      insertPreview.updatePreviews(sequencer.steps[0].imgElement.src,'.insertDiv');
```
Comment (Harshithpabbati) [inline examples/demo.js]: why did you make it insertDiv???

**Comment by HarshKhandeparkar** [comment]
😭

Ok. Can you provide a screenshot/gif(preferably gif)? Also please explain what is not working exactly. Does selectize work? Also what is the error in the console?

**Comment by HarshKhandeparkar** [comment]
Or only the quock btns are not working?

**Comment by HarshKhandeparkar** [comment]
Ok I know why the previews are not working but O don't know how to fix those. Only @Divy123 does. Can we do that in a followup?

**Comment by HarshKhandeparkar** [comment]
The error is not actually because of my pr but because of selectize

File: examples/demo.js (hunk 3 above)
Comment (HarshKhandeparkar) [reply examples/demo.js]: Because earlier it was an id, now it is a class

**Comment by Harshithpabbati** [comment]
> The error is not actually because of my pr but because of selectize

Selectize is working !!. But only the quick add buttons aren't.

**Comment by HarshKhandeparkar** [comment]
Divy has fixed the quock btns for the main step selector recently.

**Comment by Harshithpabbati** [comment]
And the most important thing is when I added the step it should again change to insert-step but it isn't changing see the close button in the saturation step.
append

**Comment by Harshithpabbati** [comment]
And one close button is enough I guess.

**Comment by HarshKhandeparkar** [comment]
Ok this does need some changes. But I cannot do anything anymore.

**Comment by Harshithpabbati** [comment]
@HarshKhandeparkar It is looking nice right??? See this this might be the smallest size in mobile.
xs

**Comment by HarshKhandeparkar** [comment]
:+1:

**Comment by Harshithpabbati** [comment]
> @HarshKhandeparkar It is looking nice right??? See this this might be the smallest size in mobile.
> xs

I didn't made any changes.

**Comment by jywarren** [comment]
Hi all - @HarshKhandeparkar don't worry, we will get this merged. @Harshithpabbati can you make a checklist of things that remain to be fixed here, and I can see if I can go through and solve them one by one and then merge this?

Don't be discouraged, you've done a tremendous amount here! We are so grateful! 🙌 we'll solve it!

**Comment by HarshKhandeparkar** [comment]
I think only one thing is left to be done.

1. When the step is inserted, the following code is to be run.
```js
toggleDiv();
```

That's it.

**Comment by HarshKhandeparkar** [comment]
@jywarren I did the changes myself. Done with this. Whew!
Please try to merge this before the others.

@Harshithpabbati try this out locally. 

### Thank you All

**Comment by HarshKhandeparkar** [comment]
I just deleted some old comments and removed old omgs because the page was taking too long to load

**Comment by HarshKhandeparkar** [comment]
@publiclab/is-reviewers please review :)

File: examples/lib/intermediateHtmlStepUi.js [hunk 4]
```diff
@@ -4,7 +4,6 @@ var urlHash = require('./urlHash.js'),
 function IntermediateHtmlStepUi(_sequencer, step, options) {
   function stepUI() {
     return '<div class="row insertDiv collapse">\
-        <div class="col-md-6 col-md-offset-2" style="margin-top:5%">\
           <section class="panel panel-primary .insert-step">\
             <button class="btn btn-default close-insert-box"><i class="fa fa-times" aria-hidden="true"></i> Close</button>\
```
Comment (Harshithpabbati) [inline examples/lib/intermediateHtmlStepUi.js]: @HarshKhandeparkar remove this line. Because you are appending the close option for two times.

Comment (Harshithpabbati) [reply examples/lib/intermediateHtmlStepUi.js]: Sorry that's not the line. Remove this line
<button class="btn btn-default close-insert-box"><i class="fa fa-times" aria-hidden="true"></i> Close</button>\

Comment (HarshKhandeparkar) [reply examples/lib/intermediateHtmlStepUi.js]: Jywarren asked me to do that

**Comment by Harshithpabbati** [comment]
@HarshKhandeparkar just one more change after changing above mentioned one. It's about the quick add buttons ! They are not working.

**Comment by Harshithpabbati** [comment]
@jywarren I have an idea of removing the quick add buttons in the insert-step we can just have the selectize one in the insert step. What are your thoughts about it ?

**Comment by HarshKhandeparkar** [comment]
@Divy123 will have to do that. I don't know how to fix it.

**Comment by HarshKhandeparkar** [comment]
Divy had fixed it for the main selector. It is some problem with selectize.

File: examples/lib/intermediateHtmlStepUi.js (hunk 4 above)
Comment (Harshithpabbati) [reply examples/lib/intermediateHtmlStepUi.js]: ok remove the above line which I mentioned.

Comment (HarshKhandeparkar) [reply examples/lib/intermediateHtmlStepUi.js]: Jywarren asked me to add a close button inside the box itself.

Comment (Harshithpabbati) [reply examples/lib/intermediateHtmlStepUi.js]: Oh but it looks odd if we have two buttons for the same option.

Comment (HarshKhandeparkar) [reply examples/lib/intermediateHtmlStepUi.js]: Most of the times, the other btn will be unnoticed. If by mistake someone opens the box, the btn that is used to open the dialog, can be used to close it.

**Comment by HarshKhandeparkar** [comment]
@jywarren what about this? Will I have to rebase it again because of grid overlay?

**Comment by Harshithpabbati** [comment]
@HarshKhandeparkar no need there is no conflict right???

**Comment by HarshKhandeparkar** [comment]
I was asking if I'll have to rebase. @jywarren please try to review and merge this.

**Comment by Harshithpabbati** [comment]
@jywarren this is ready to merge. And @Divy123 will fix the quick add buttons.

**Comment by Divy123** [comment]
Surely I will.

**Comment by Harshithpabbati** [comment]
@jywarren do you think we need two close buttons ?

**Comment by HarshKhandeparkar** [comment]
Thanks a lot @Divy123

**Comment by Harshithpabbati** [comment]
@jywarren this is ready to merge :smile:

**Comment by Harshithpabbati** [comment]
A great work by @harshkhandeparkar :+1:

**Comment by HarshKhandeparkar** [comment]
You helped me a lot in it. :heart:
@Harshithpabbati @Divy123 @jywarren

**Comment by HarshKhandeparkar** [comment]
This wouldn't have been possibke without the help and feedback everyone provided.

**Comment by Harshithpabbati** [comment]
That's just because of open source  💓

**Comment by jywarren** [comment]
SOOOOO GREAAAATTTTT!!!! 🎉 🎉 🎉 🎉 🎉 🎉
