### PR TITLE
fixed registration problem of service worker

### LINKED ISSUE #1138: Service worker registration failed error in console
```js
Service worker registration failed, error: TypeError: Cannot set property 'onstatechange' of null
    at image-sequencer-ui.js:229
```

The above error appears everytime in browser console.

### PR DESCRIPTION
**Pull request by vivek-30**
Fixes #1138.

### CODE REVIEW

**Comment by vivek-30** [comment]
@HarshKhandeparkar , @jywarren  Could you please review this ☺️

File: examples/lib/cache.js [hunk 1]
```diff
@@ -29,24 +29,19 @@ var setupCache = function() {
...
+                    location.reload();
+                  })
                 }
                 // No updates available; do nothing.
                 break;
             }
-          });
-        });
-
-        const installingWorker = registration.installing;
```
Comment (vivek-30) [inline examples/lib/cache.js:39]: this is happening bcoz we have already checked service worker state as installed and now this state `installing` will  not come again. so it returns a null on which we have just added a `statechange` event listener which is meaningless.

Comment (jywarren) [reply examples/lib/cache.js:39]: I see, thank you!; this is so hard to track as maintainers; do you think it's possible to write a test for this?

Comment (vivek-30) [reply examples/lib/cache.js:39]: I have tried to write test for this but i don't know how to make this run 😅  ? 

you can have a look this test -
https://github.com/vivek-30/image-sequencer/blob/5fc7fc8ecbb02ac989605a4d422b7b8d85d67aeb/test/core/sw.test.js#L1-L72

@jywarren, @HarshKhandeparkar  could you please suggest me what to do?

Comment (vivek-30) [reply examples/lib/cache.js:39]: Actually @jywarren  what i think is even if we don't build a test for this then also it will solve this problem.
No doubt that adding test will ensure more security and safety but don't think it will slow down image sequencer as to check a successful installation of sw .we have to remove existing sw and clear out the cache and then register a new updated sw (which i have done in my test) ?

Comment (jywarren) [reply examples/lib/cache.js:39]: Thanks for giving it a try! If you add the test to the correct folder alongside others in this repo, it'll run within this PR. It's possible you need to add some more assertions -- like, see how this line confirms something we expect to be true about the test scenario:

https://github.com/publiclab/image-sequencer/blob/eb81b7de4b331dc32684e90ee9898520c80c14e4/test/core/sequencer/chain.js#L16

Want to try adding your test in this PR?

Comment (vivek-30) [reply examples/lib/cache.js:39]: @jywarren plz have a look now ,i have added a test for this. Hope you like it ☺️

File: test/core/sequencer/sw.js [hunk 2]
```diff
@@ -0,0 +1,72 @@
+var sw = require('../../examples/sw');
+var test = require('tape');
+
+function SWInstallation(registration){
```
Comment (jywarren) [inline test/core/sequencer/sw.js:4]: Here, should we instead use the `setupCache()` method from our actual code, rather than make a unique worker management code segment within the tests? Does that make sense? What do you think? Then our assertions below ought to still pass, right?

Comment (vivek-30) [reply test/core/sequencer/sw.js]: sure sir ,it will avoid code duplication.
And i also thinks it will still pass.☺️

Comment (vivek-30) [reply test/core/sequencer/sw.js]: @jywarren could you please review these changes ☺️

**Review by jywarren — APPROVED** [review]

**Comment by jywarren** [comment]
Thanks for sticking with this one @vivek-30 this was a complex one to fix and test and we appreciate it!!!!

**Comment by vivek-30** [comment]
Thanks a lot sir 😊 . you really helped me to solve the issue.
